Current issue:

Starting simulation. This may take a moment...
Initial balances:
Balances for Alice:
Traceback (most recent call last):
  File "C:\Users\Johnson\Desktop\School\cs168\CS168-Final-Project-main\CS168-Final-Project-main\driver.py", line 22, in <module>
    alice.show_all_balances()
  File "C:\Users\Johnson\Desktop\School\cs168\CS168-Final-Project-main\CS168-Final-Project-main\client.py", line 72, in show_all_balances
    for address, balance in self.blocks[-1].balances.items():
                            ~~~~~~~~~~~^^^^
KeyError: -1